//! Gateway 平台接入字段的受管配置元数据。
//!
//! 这里只声明平台模块自己理解的字段；Core 配置中心通过根进程注入后统一编排，
//! 不需要反向理解 QQ、OneBot 或微信协议细节。

use qq_maid_core::config::center::{
    ManagedConfigApplyMode as Apply, ManagedConfigField as Field,
    ManagedConfigValueType as ValueType,
};

pub fn managed_config_fields() -> Vec<Field> {
    vec![
        Field::public(
            "platform.qq_official.enabled",
            "QQ_BOT_ENABLED",
            "gateway.qq_official",
            ValueType::Boolean,
            Apply::Restart,
            Some("true"),
        ),
        Field::secret(
            "platform.qq_official.app_id",
            "QQ_BOT_APP_ID",
            "gateway.qq_official",
            Apply::Restart,
        )
        .with_env_aliases(&["QQ_APPID"]),
        Field::secret(
            "platform.qq_official.app_secret",
            "QQ_BOT_APP_SECRET",
            "gateway.qq_official",
            Apply::Restart,
        )
        .with_env_aliases(&["QQ_SECRET"]),
        Field::public(
            "platform.onebot11.enabled",
            "ONEBOT11_ENABLED",
            "gateway.onebot11",
            ValueType::Boolean,
            Apply::Restart,
            Some("false"),
        ),
        Field::public(
            "platform.onebot11.bind_host",
            "ONEBOT11_BIND_HOST",
            "gateway.onebot11",
            ValueType::String,
            Apply::Restart,
            Some("127.0.0.1"),
        ),
        Field::public(
            "platform.onebot11.bind_port",
            "ONEBOT11_BIND_PORT",
            "gateway.onebot11",
            ValueType::Integer,
            Apply::Restart,
            Some("8789"),
        ),
        Field::public(
            "platform.onebot11.websocket_path",
            "ONEBOT11_WEBSOCKET_PATH",
            "gateway.onebot11",
            ValueType::String,
            Apply::Restart,
            Some("/onebot/v11/ws"),
        ),
        Field::secret(
            "platform.onebot11.access_token",
            "ONEBOT11_ACCESS_TOKEN",
            "gateway.onebot11",
            Apply::Restart,
        ),
        Field::public(
            "platform.wechat_service.enabled",
            "WECHAT_SERVICE_ENABLED",
            "gateway.wechat_service",
            ValueType::Boolean,
            Apply::Restart,
            Some("false"),
        ),
        Field::secret(
            "platform.wechat_service.token",
            "WECHAT_SERVICE_TOKEN",
            "gateway.wechat_service",
            Apply::Restart,
        ),
        Field::secret(
            "platform.wechat_service.app_id",
            "WECHAT_SERVICE_APP_ID",
            "gateway.wechat_service",
            Apply::Restart,
        ),
        Field::secret(
            "platform.wechat_service.app_secret",
            "WECHAT_SERVICE_APP_SECRET",
            "gateway.wechat_service",
            Apply::Restart,
        ),
        Field::public(
            "platform.wechat_service.encryption_mode",
            "WECHAT_SERVICE_ENCRYPTION_MODE",
            "gateway.wechat_service",
            ValueType::String,
            Apply::Restart,
            Some("plaintext"),
        ),
        Field::secret(
            "platform.wechat_service.encoding_aes_key",
            "WECHAT_SERVICE_ENCODING_AES_KEY",
            "gateway.wechat_service",
            Apply::Restart,
        ),
        Field::public(
            "platform.wechat_service.bind_host",
            "WECHAT_SERVICE_BIND_HOST",
            "gateway.wechat_service",
            ValueType::String,
            Apply::Restart,
            Some("127.0.0.1"),
        ),
        Field::public(
            "platform.wechat_service.bind_port",
            "WECHAT_SERVICE_BIND_PORT",
            "gateway.wechat_service",
            ValueType::Integer,
            Apply::Restart,
            Some("8788"),
        ),
        Field::public(
            "platform.wechat_service.callback_path",
            "WECHAT_SERVICE_CALLBACK_PATH",
            "gateway.wechat_service",
            ValueType::String,
            Apply::Restart,
            Some("/wechat/service"),
        ),
    ]
}
